export const App_Info = {
  name: ["Tokyo", "Sounds"],
  title: "Tokyo Sounds",
  subtitle: "Tokyo Sounds is a platform for creating and sharing sounds.",
  description: "Tokyo Sounds is a platform for creating and sharing sounds.",
  image: "./images/default.png",
  logo: "./images/default.png",
  github: "https://github.com/default",
};

export const MEMBER_LIST = [
  {
    "name": "default",
    "slug": "default",
    "hiragana": "ああああ",
    "role": "user",
    "email": "default@example.com",
    "description": "Default constraint",
    "image": "./images/default.png",
    "portfolio": "./images/default.png",
    "github": "https://github.com/default",
  },
  {
    "name": "default",
    "slug": "default",
    "hiragana": "ああああ",
    "role": "user",
    "email": "default@example.com",
    "description": "Default constraint",
    "image": "./images/default.png",
    "portfolio": "./images/default.png",
    "github": "https://github.com/default",
  },
  {
    "name": "default",
    "slug": "default",
    "hiragana": "ああああ",
    "role": "user",
    "email": "default@example.com",
    "description": "Default constraint",
    "image": "./images/default.png",
    "portfolio": "./images/default.png",
    "github": "https://github.com/default",
  },
  {
    "name": "default",
    "slug": "default",
    "hiragana": "ああああ",
    "role": "user",
    "email": "default@example.com",
    "description": "Default constraint",
    "image": "./images/default.png",
    "portfolio": "./images/default.png",
    "github": "https://github.com/default",
  },
  {
    "name": "default",
    "slug": "default",
    "hiragana": "ああああ",
    "role": "user",
    "email": "default@example.com",
    "description": "Default constraint",
    "image": "./images/default.png",
    "portfolio": "./images/default.png",
    "github": "https://github.com/default",
  },
  {
    "name": "default",
    "slug": "default",
    "hiragana": "ああああ",
    "role": "user",
    "email": "default@example.com",
    "description": "Default constraint",
    "image": "./images/default.png",
    "portfolio": "./images/default.png",
    "github": "https://github.com/default",
  }
];