/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cudecity_test02.glb --output src/components/CudecityTest02Model.tsx --typescript 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
  };
  materials: {};
  animations: GLTFAction[];
};

export function CudecityTest02Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/cudecity_test02.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -0.1, 0]}>
        <planeGeometry args={[1000, 1000]} />
        <meshStandardMaterial color="#808080" roughness={0.8} metalness={0.1} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/cudecity_test02.glb");
