/*
3Dモデルファイル: 3D Model File
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\CLASS-ROOM\mirai-souzou\tokyo-sounds\public\3dtest.glb --output C:\CLASS-ROOM\mirai-souzou\tokyo-sounds\src\components\Model.tsx --typescript --transform 
Files: C:\CLASS-ROOM\mirai-souzou\tokyo-sounds\public\3dtest.glb [3.06MB] > C:\CLASS-ROOM\mirai-souzou\tokyo-sounds\src\components\3dtest-transformed.glb [147.29KB] (95%)
Author: antonmoek (https://sketchfab.com/antonmoek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-lowpoly-small-city-free-pack-edd1c604e1e045a0a2a552ddd9a293e6
Title: Cartoon Lowpoly Small City Free Pack

GLBモデルをロードして表示するコンポーネント - Component to load and display GLB model
東京のランドマークや建物を3Dで表示するためのコンポーネント - Component for displaying Tokyo landmarks and buildings in 3D
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTFResult } from '@/types/model'  // TypeScriptの型定義をインポート - Import TypeScript type definitions

// モデルの事前読み込み - Preload the model for better performance
useGLTF.preload('/3dtest-transformed.glb')

// 3Dモデルコンポーネント - 3D Model Component
export function Model(props: JSX.IntrinsicElements['group']) {
  // useGLTFフックでGLBモデルを読み込む - Load GLB model using useGLTF hook
  const { nodes, materials } = useGLTF('/3dtest-transformed.glb') as GLTFResult
  
  // モデルのルート要素に参照を設定 - Set reference for the model's root element
  const groupRef = useRef<THREE.Group>(null)
  
  // 3Dモデルの表示 - Display the 3D model
  return (
    <group 
      ref={groupRef}
      {...props} 
      dispose={null}
      // Add any additional transformations or interactions here in future tasks
    >
      {/* 車3号 - Car 3 */}
      <mesh 
        geometry={nodes.CAR_03_1_World_ap_0.geometry} 
        material={materials.World_ap} 
        position={[-346.938, -76.04, -1395.23]} 
        rotation={[-Math.PI, 0.732, Math.PI]} 
        scale={1.5} 
      />
      
      {/* 車8号 - Car 8 */}
      <mesh 
        geometry={nodes.Car_08_4_World_ap8_0.geometry} 
        material={materials['World_ap_8'] || materials['World_ap.8']} 
        position={[569.751, -103.644, -166.073]} 
        rotation={[Math.PI / 2, 0, -Math.PI / 2]} 
        scale={1.5} 
      />
    </group>
  )
}
